name: CI

on:
  pull_request:
    branches: [ develop, main ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ "1.22" ]
        node-version: [ "20" ]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with: { go-version: ${{ matrix.go-version }} }
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - run: pnpm install --frozen-lockfile
      - run: go work sync
      - run: task lint
      - run: task test
